package com.usalko.test.intproc;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.usalko.test.intproc.cmd.CmdCount;
import com.usalko.test.intproc.cmd.Command;
import com.usalko.test.intproc.storage.InMemoryIntegerRepository;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class CommandProcessorTest extends AbstractIntProcTest {
    @Test public void testExec() throws IntProcException {
        InMemoryIntegerRepository repository = new InMemoryIntegerRepository();
        ErrorProcessor errorProcessor = new ErrorProcessor();

        Command cmdCount = new CmdCount();

        CommandProcessor commandProcessor = new CommandProcessor(repository, errorProcessor);

        assertEquals("Чисел в наборе: 0", commandProcessor.exec(cmdCount,
                SimpleExecContext.context(repository, commandProcessor.registry(),
                        cmdCount, "count")));
    }
}
